/* eslint-disable no-shadow */

export enum EStatusType {
  ORDER_ACCEPTED = 'ORDER_ACCEPTED',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAID = 'PAID',
  WAITING_FOR_PAYMENT = 'WAITING_FOR_PAYMENT',
  PRODUCED = 'PRODUCED',
  SHIPPING_TO_VIETNAM = 'SHIPPING_TO_VIETNAM',
  SHIPPED_TO_VIETNAM = 'SHIPPED_TO_VIETNAM',
  WAITING_FOR_PAYMENT_OF_SURCHARGE = 'WAITING_FOR_PAYMENT_OF_SURCHARGE',
  SURCHARGE_PAID = 'SURCHARGE_PAID',
  IN_TRANSIT = 'IN_TRANSIT',
  PREPARING_GOODS = 'PREPARING_GOODS',
  GOODS_READY = 'GOODS_READY',
  TRANSFERRING_TO_SHIPPING_UNIT = 'TRANSFERRING_TO_SHIPPING_UNIT',
  SENT_TO_SHIPPING_UNIT = 'SENT_TO_SHIPPING_UNIT',
  ON_DELIVERY = 'ON_DELIVERY',
  FINISHED = 'FINISHED',
  CANCELLED = 'CANCELLED',
}
