export const ZERO = 0
export const SALT_ROUNDS = 10

export const SECOND_PER_MINUTE = 60
export const MINUTE_PER_HOUR = 60
export const HOUR_PER_DAY = 24
export const DAY_PER_WEEK = 7

export const MILLIESCOND_PER_SECOND = 1000
export const MILLIESCOND_PER_MINUTE = MILLIESCOND_PER_SECOND * SECOND_PER_MINUTE
export const MILLIESCOND_PER_HOUR = MILLIESCOND_PER_MINUTE * MINUTE_PER_HOUR
export const MILLIESCOND_PER_DAY = MILLIESCOND_PER_HOUR * HOUR_PER_DAY
export const MILLIESCOND_PER_WEEK = MILLIESCOND_PER_DAY * DAY_PER_WEEK
export const PIPE_TIMEOUT = 5000

export const DEFAULT_PORT = 9300
export const DEFAULT_DB_PORT = 3306

export const CUSTOMER_ADDRESS_LIMIT = 5

export const DEFAULT_LIMIT = 15

export const OTP_EXPIRE_TIME_BY_MINUTE = 5
export const OTP_EXPIRE_TIME = OTP_EXPIRE_TIME_BY_MINUTE * SECOND_PER_MINUTE * MILLIESCOND_PER_SECOND

// DATABASE
export const MAX_VARCHAR_LENGTH = 255
